services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: wojtek
      SPRING_DATASOURCE_PASSWORD: haslo
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: wojtek
      POSTGRES_PASSWORD: haslo
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 